// socket
export const SET_WEBSOCKET = "SET_WEBSOCKET";
export const SET_SOCKET_CONNECTION = "SET_SOCKET_ON_CONNECTION";
export const UPDATE_IS_CONNECTED = "UPDATE_IS_CONNECTED";
export const SET_LAST_SOME_LINES = "SET_LAST_SOME_LINES";